"""update job table

Revision ID: 1021541856ab
Revises: bfa0dc02879b
Create Date: 2026-02-01 09:13:59.810698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1021541856ab'
down_revision: Union[str, Sequence[str], None] = 'bfa0dc02879b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('idempotency_key', sa.String(length=128), nullable=True))
    op.add_column('jobs', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('jobs', sa.Column('succeeded_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_jobs_idempotency_key'), 'jobs', ['idempotency_key'], unique=True)
    op.drop_column('jobs', 'result_location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('result_location', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_jobs_idempotency_key'), table_name='jobs')
    op.drop_column('jobs', 'succeeded_at')
    op.drop_column('jobs', 'started_at')
    op.drop_column('jobs', 'idempotency_key')
    # ### end Alembic commands ###
