"""add attempts and run_after

Revision ID: 8e144e100cdc
Revises: 248b5922dd2c
Create Date: 2026-01-24 08:39:08.582246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e144e100cdc'
down_revision: Union[str, Sequence[str], None] = '248b5922dd2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "jobs",
        sa.Column("attempts", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "jobs",
        sa.Column("max_attempts", sa.Integer(), nullable=False, server_default="5"),
    )
    op.add_column(
        "jobs",
        sa.Column("run_after", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index(
        op.f("ix_jobs_run_after"),
        "jobs",
        ["run_after"],
        unique=False,
    )

    op.alter_column("jobs", "attempts", server_default=None)  # Remove default if you prefer app-controlled defaults
    op.alter_column("jobs", "max_attempts", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_run_after'), table_name='jobs')
    op.drop_column('jobs', 'run_after')
    op.drop_column('jobs', 'max_attempts')
    op.drop_column('jobs', 'attempts')
    # ### end Alembic commands ###
